#! /bin/bash
mkdir -p {$1,temp/Dir1,temp/Dir2,temp/Dir1/Dir3,temp/Dir1/Dir3/Dir4}
touch {$1/Dir1/File1,temp/Dir2/File2,temp/Dir1/Dir3/Dir4/File4,temp/Dir1/Dir3/Dir4/File3}
chmod 400 $1/Dir1/File1
chmod 666 $1/Dir1/Dir3/Dir4/File4
chmod 200 $1/Dir1/Dir3/Dir4/File3
chmod 750 $1/Dir1/Dir3/Dir4
chmod 000 $1/Dir1/Dir3
chmod 770 $1/Dir1
chmod 775 $1/Dir2
chmod 640 $1/Dir2/File2
